# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import sys


class Main_ui(object):
    def __init__(self, Dialog, win_w, win_h):
        frame_h = int(win_w/10)
        frame_h_2 = int(frame_h/2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, (win_h-frame_h), (win_w), (frame_h)))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.Item_b = QtWidgets.QPushButton(self.frame)
        self.Item_b.setGeometry(QtCore.QRect(0, 0, frame_h, frame_h_2))
        self.Item_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Item_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Item_b.setGraphicsEffect(self.opacity_effect)
        self.Item_b.setObjectName("Item_b")
        self.Stats_b = QtWidgets.QPushButton(self.frame)
        self.Stats_b.setGeometry(QtCore.QRect(frame_h, 0, frame_h, frame_h_2))
        self.Stats_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Stats_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Stats_b.setGraphicsEffect(self.opacity_effect)
        self.Stats_b.setObjectName("Stats_b")
        self.Summons_b = QtWidgets.QPushButton(self.frame)
        self.Summons_b.setGeometry(QtCore.QRect(frame_h*2, 0, frame_h, frame_h_2))
        self.Summons_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Summons_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Summons_b.setGraphicsEffect(self.opacity_effect)
        self.Summons_b.setObjectName("Summons_b")
        self.Skills_b = QtWidgets.QPushButton(self.frame)
        self.Skills_b.setGeometry(QtCore.QRect(frame_h*3, 0, frame_h, frame_h_2))
        self.Skills_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Skills_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Skills_b.setGraphicsEffect(self.opacity_effect)
        self.Skills_b.setObjectName("Skills_b")
        self.Forge_b = QtWidgets.QPushButton(self.frame)
        self.Forge_b.setGeometry(QtCore.QRect(frame_h*4, 0, frame_h, frame_h_2))
        self.Forge_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Forge_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Forge_b.setGraphicsEffect(self.opacity_effect)
        self.Forge_b.setObjectName("Forge_b")
        self.Equips_b = QtWidgets.QPushButton(self.frame)
        self.Equips_b.setGeometry(QtCore.QRect(frame_h*5, 0, frame_h, frame_h_2))
        self.Equips_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Equips_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Equips_b.setGraphicsEffect(self.opacity_effect)
        self.Equips_b.setObjectName("Equips_b")
        self.Map_b = QtWidgets.QPushButton(self.frame)
        self.Map_b.setGeometry(QtCore.QRect(frame_h*6, 0, frame_h, frame_h_2))
        self.Map_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Map_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Map_b.setGraphicsEffect(self.opacity_effect)
        self.Map_b.setObjectName("Map_b")
        self.Info_b = QtWidgets.QPushButton(self.frame)
        self.Info_b.setGeometry(QtCore.QRect(frame_h*7, 0, frame_h, frame_h_2))
        self.Info_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Info_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Info_b.setGraphicsEffect(self.opacity_effect)
        self.Info_b.setObjectName("Info_b")
        self.Options_b = QtWidgets.QPushButton(self.frame)
        self.Options_b.setGeometry(QtCore.QRect(frame_h*8, 0, frame_h, frame_h_2))
        self.Options_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Options_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Options_b.setGraphicsEffect(self.opacity_effect)
        self.Options_b.setObjectName("Options_b")
        self.Save_b = QtWidgets.QPushButton(self.frame)
        self.Save_b.setGeometry(QtCore.QRect(frame_h*9, 0, frame_h, frame_h_2))
        self.Save_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Save_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Save_b.setGraphicsEffect(self.opacity_effect)
        self.Save_b.setObjectName("Save_b")
        self.Money_b = QtWidgets.QPushButton(self.frame)
        self.Money_b.setGeometry(QtCore.QRect(0, frame_h_2, int(win_w/7.1), frame_h_2))
        self.Money_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Money_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Money_b.setGraphicsEffect(self.opacity_effect)
        self.Money_b.setObjectName("Money_b")
        self.Players_b = QtWidgets.QPushButton(self.frame)
        self.Players_b.setGeometry(QtCore.QRect(int(win_w/7.1), frame_h_2, int(win_w/2.105), frame_h_2))
        self.Players_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Players_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Players_b.setGraphicsEffect(self.opacity_effect)
        self.Players_b.setObjectName("Players_b")
        self.Backup_b = QtWidgets.QPushButton(self.frame)
        self.Backup_b.setGeometry(QtCore.QRect(int(win_w/1.63), frame_h_2, int(win_w/3.3), frame_h_2))
        self.Backup_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Backup_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Backup_b.setGraphicsEffect(self.opacity_effect)
        self.Backup_b.setObjectName("Backup_b")
        self.Quit_b = QtWidgets.QPushButton(self.frame)
        self.Quit_b.setGeometry(QtCore.QRect(int(win_w/1.095), frame_h_2, int(win_w/11.5), frame_h_2))
        self.Quit_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Quit_b.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 0);")
        self.opacity_effect = QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0)
        self.Quit_b.setGraphicsEffect(self.opacity_effect)
        self.Quit_b.setObjectName("Quit_b")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(0, 0, win_w, frame_h))
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setLineWidth(0)
        self.label_2.setPixmap(QtGui.QPixmap("intface.PNG"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.Item_b.raise_()
        self.Stats_b.raise_()
        self.Summons_b.raise_()
        self.Skills_b.raise_()
        self.Forge_b.raise_()
        self.Equips_b.raise_()
        self.Map_b.raise_()
        self.Save_b.raise_()
        self.Info_b.raise_()
        self.Options_b.raise_()
        self.Quit_b.raise_()
        self.Backup_b.raise_()
        self.Money_b.raise_()
        self.Players_b.raise_()



